import { U } from '../runtime/defs.js';
export declare function Eval_multiply(p1: U): U;
export declare function multiply(arg1: U, arg2: U): U;
export declare function multiply_noexpand(arg1: U, arg2: U): U;
export declare function multiply_all(n: U[]): U;
export declare function multiply_all_noexpand(arr: U[]): U;
export declare function divide(p1: U, p2: U): U;
export declare function inverse(p1: U): U;
export declare function reciprocate(p1: U): U;
export declare function negate(p1: U): U;
export declare function negate_noexpand(p1: U): U;
